### ISSUE TITLE
Getting rid of `compileLBJ.sh` script and using the lbj-maven-plugin

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/lbjava#18]
There is this script `compileLBJ.sh` in the `lbjava-examples/` which is used to generate the java files for example inside this module, before being able to compile the whole project. 

This is really a temporary solution and we should be able to bypass this step with `lbjava-maven-plugin`. 

Proposal: remove the script and just use the lbjava maven plugin. 

@mayhewsw do you think you have take a stab at this? 

FYI @christos-c

**Comment by danyaljj** [comment]
A suggestion by Christos; using profiles: http://stackoverflow.com/questions/15040606/maven-plugin-as-module

**Comment by bhargav** [comment]
Fixed by PR #42 Merged to master. Issue can be closed.
