### ISSUE TITLE
Using inference project as dependency

### ISSUE THREAD

**Issue by christos-c** [IllinoisCogComp/lbjava#53]
The [inference package](https://gitlab-beta.engr.illinois.edu/cogcomp/inference) offers a nice abstraction over various ILP (and non-ILP) inference algorithms and hooks (just ported oj! there).

It would be nice to have LBJava's inference classes drawn from this package, since it'll be easier to update and maintain.

**Comment by danyaljj** [comment]
Do these have to be separate projects?

**Comment by christos-c** [comment]
yes, because I don't want to have to import LBJava only to use the inference hooks.

**Comment by danyaljj** [comment]
Or maybe maybe LBJava should be dependent on this package? Just to get rid of duplications ....

**Comment by christos-c** [comment]
Yes, that's what I'm suggesting. To add this package as a dependency to LBJava.

**Comment by danr-ccg** [comment]
Hi,

One plan I had, which I think we have discussed, is to augment the inference library with other inference approaches. The formulation should be the same as we have now, though, so it does not impact the programmer. Will this allow it?

            Dan

**Comment by christos-c** [comment]
Yes, that's definitely part of the motivation. The other part would be to able to use these inference algorithms outside LBJava (e.g. illinois-sl, Saul) via a unified interface.

**Comment by danyaljj** [comment]
Relevant: Google's or-tools: https://github.com/google/or-tools
