### ISSUE TITLE
Why sort inside vectors 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/lbjava#66]
Why all these sort functions inside? I don't understand the logic ...: 
https://github.com/IllinoisCogComp/lbjava/blob/master/lbjava/src/main/java/edu/illinois/cs/cogcomp/lbjava/util/DVector.java#L189-L192
https://github.com/IllinoisCogComp/lbjava/blob/master/lbjava/src/main/java/edu/illinois/cs/cogcomp/lbjava/util/DVector2D.java#L236-L238
https://github.com/IllinoisCogComp/lbjava/blob/master/lbjava/src/main/java/edu/illinois/cs/cogcomp/lbjava/util/FVector.java#L197-L200
https://github.com/IllinoisCogComp/lbjava/blob/master/lbjava/src/main/java/edu/illinois/cs/cogcomp/lbjava/util/OVector.java#L201-L203

**Comment by christos-c** [comment]
The reason is stated below in the `binarySearch` method:

>  This vector **must** be sorted (as by the `sort()` method) prior to making this call.

**Comment by danyaljj** [comment]
FYI @cowchipkid
