### ISSUE TITLE
copy dependencies necessary for java-cup? 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/lbjava#77]
The comment [here](https://github.com/IllinoisCogComp/lbjava/blob/master/lbjava/pom.xml#L117-L119) says the `copy-dependencies` stage is necessary for java cup. I commented it out and ran `mvn test` and  nothing broke. Is it fine to drop this goal? 

Why am I asking this?: suppose we add another module, on which lbjava depends (e.g. inference). If the dependency is not already deployed, `copy-dependencies` would fail.

**Comment by christos-c** [comment]
I would be happy to drop this *if* you make sure it doesn't affect the compilation of the language itself (`yylex` and `parser`), neither of which will show in the `test` phase unless you start completely from scratch (clean computer, clean repo).

**Comment by christos-c** [comment]
I take it this is no longer a problem @danyaljj?
